### ISSUE TITLE
create-migration

### ISSUE THREAD

**Issue by AlessandroPagliuca** [AlessandroPagliuca/creator-game#1]
Ciao Giuseppe questi sono i dati della tabella:
name VARCHAR(50),
level INT,
class VARCHAR(50),
race VARCHAR(50),
lifepoint INT,
strenght INT,
agility INT,
main_weapon VARCHAR(50),

**Comment by AlessandroPagliuca** [comment]
git fetch origin
git checkout 1-create-migration

**Comment by GiuseppeIndomenico** [comment]
ho commitato la migration nel db
